### PR TITLE
A user can make a product recommendation to another user

### PR DESCRIPTION
**Pull request by wocaldwell**
## Description
1. Name of Branch:
`wc-notify-complete`

2. Tickets related to PR (with links):
[User can recommend product to another user](https://github.com/handy-pandas/djangazon/issues/20)

3. Feature/Fix Description:
In the `product detail` view a user can click on the ` Recommend this Product` link.
The view changes and the user can manually enter the name of another user.
When the user clicks on the `send notification` button IF the username is valid the user is directed to the previous product detail view. IF the username is invalid the form reloads.

TO TEST:
Create a user and then log out and create another user. Now recommend a product to the user you previously created. Now log in to that user and the notification icon should have increased by one.

4. What architectual changes made:
changed `USE_TZ = False` in `settings.py`
added `Recommendation` class, `get_recommendations_notifications` function and `User.add_to_class('get_recommendations_notifications', get_recommendations_notifications)` to `models.py`
added `viewrecommended_product.py` file
added `RecommendationFactory ` class to `website/factories.py`
added `website/forms/form_recomend.py` file
added `RecommendationFactory.create_batch(size=5)` to `website/management/commands/builddb.py`
and many more!!

5. Any dependency changes:
No

## Testing
1. New Unit Tests:
No

2. All Tests Pass:
Yes

## Documentation
1. Fully completed Documentation with signature:
Yes

2. Readme file updated:
No

## Deployment
1. Any new migrations to run:
```
python manage.py deletedb
python manage.py builddb
```

### CODE REVIEW

**Comment by leead4** [comment]
looks good! It does what you said it did.

**Review by ANMyers — DISMISSED** [review]
She works, but remind me to relook at it once you've merged master

**Review by ANMyers — CHANGES_REQUESTED** [review]
i notice that 'Rate' is still a table in sqlite3 but the ability to rate the product is missing from the html, the functionality seems to still live in the views, but the radio buttons and average rating is missing. to be more specific

what was line 19 in my_products.html:
```<li>Average Rating: {{ product.get_average_rating }}</li>``` 

what was line 22-31 in order_details.html:
```<form method="post" action="{% url 'website:order_details' order_id %}">```
```                     {% csrf_token %}```
```                     <input name="product_id" type="hidden" value="{{ product.id }}"/>```
```                     <label>1<input name="rate" type="radio" value="1" {% if product.rating == 1 %} checked {% endif %}/></label>```
```                     <label>2<input name="rate" type="radio" value="2"{% if product.rating == 2 %} checked {% endif %}/></label>```
```                     <label>3<input name="rate" type="radio" value="3"{% if product.rating == 3 %} checked {% endif %}/></label>```
```                     <label>4<input name="rate" type="radio" value="4"{% if product.rating == 4 %} checked {% endif %}/></label>```
 ```                    <label>5<input name="rate" type="radio" value="5"{% if product.rating == 5 %} checked {% endif %}/></label>```
 ```                    <input class="btn btn-success" type="submit" value="Rate!"/>```
```                 </form>```

what was line 47 in profile.html:
```<p><strong>Average Rating:</strong> {{ average_rating }}</p>``` 

i did some digging and found that this missing text is not your fault, nick did a good job styling just may have missed some lines is all, it was erased on june 5th at 3:54pm from a merge from nrn [Merge #68 ](https://github.com/handy-pandas/djangazon/commit/4d9fe04cab553bd2191ed3974f2bf969eb89eb96). no worries though if you could just add it back it works fine.

**Review by ANMyers — DISMISSED** [review]

**Review by talbotlawrence — APPROVED** [review]
Looks good!

**Pull request merged**
